[dist]
  base = "dist"
  publish = "dist"
  functions = "netlify/functions"  # Asegúrate de que apunte a la carpeta de funciones

[dev]
  functions = "netlify/functions"  # También configura el entorno de desarrollo

